site_name: MkDocs
site_description: MkDocs Material Starter Kit. Deploy documentation to hosting platforms (Netlify, GitHub Pages).
site_author: Alex Creio
# site_url: https://mkdocs.netlify.com/

# Repository
repo_name: creio/mkdocs
repo_url: https://github.com/creio/mkdocs
# edit_uri: edit/master
edit_uri: ""
# Copyright
copyright: 'Copyright &copy; Alex Creio'

# Page tree
nav:
  - Home: index.md

# Configuration
theme:
  name: material
  # 404 page
  # static_templates:
    # - 404.html
  language: ru
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  search:
    language: 'en, ru'
  social:
    - type: github
      link: https://github.com/creio

extra_css:
  - assets/css/custom.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
