site_name: Awesome ArchLinux
site_url: https://awesome-python.com
site_description: A curated list of awesome ArchLinux frameworks, libraries and software
site_author: Alex Creio
repo_name: creio/awesome-arch
repo_url: https://github.com/creio/awesome-arch
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
      link: https://github.com/creio
# google_analytics:
#   - UA-510626-7
#   - auto
extra_css:
    - css/extra.css
nav:
  - "Home": "index.md"
