site_name: Awesome ArchLinux
site_url: https://awesome-arch.netlify.com/
site_description: A curated list of awesome ArchLinux frameworks, libraries and software
site_author: Alex Creio
repo_name: creio/awesome-arch
repo_url: https://github.com/creio/awesome-arch
# edit_uri: edit/master
copyright: 'Copyright &copy;'

theme:
  language: 'ru'
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  # favicon: 'assets/images/favicon.ico'

extra:
  search:
    language: 'en, ru'
  social:
    - type: github
      link: https://github.com/creio
# google_analytics:
#   - UA-510626-7
#   - auto
extra_css:
    - assets/css/extra.css
nav:
  - "Home": "index.md"
  - "Start": "start"
  # - "Getting started":
  #     - "Start": "start"
